import ActionButton from "../../partials/ActionButton";

export const childInfo = [
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/ala-d.jpg",
    name: "Ala D",
    age: "12",
    birthday: "Jun 27, 2013",
    story: "My Story",
    desc: "Ala and his brother were abandoned on a bus that was traveling through the San Pablo City area.  When the driver discovered their abandonment he immediately contacted local authorities.  Search was made for the family but their identity was unknown.  Ala and his brother recently came into the care of Face the Children and are integrating well.  Ala is enrolled in an Independent Educational Program within Frontline Christian Academy which will tutor him to enroll at his appropriate school level.",
    link: "",
  },
  {
    image: "./img/opt-angelica.jpg",
    name: "Angelita A- Special Education",
    age: "33",
    birthday: "Jun 6, 1992",
    story: "My Story",
    desc: "She has been diagnosed with Cerebral palsy, and also being mentally slow. Angi is mostly crippled in both legs, and has limited use of her hands. For many years when she was just a small child, all she did was beg for alms in the city marketplace, along with her brothers and sisters. When Frontline missionaries noticed her, they began helping Angie by carrying her to the FTC Daycare Center where street kids were being fed and ministered to each day. At first Angie\\'s mother did not allow her to go back, and preferred she remain on the streets to collect money. Eventually Social Services escalated the case, and the FTC staff were allowed to rescue Angie from a dangerous and abusive situation, and Angie was brought to the FTC care center permanently. Though limited mentally due to her particular disease, Angie is happy because she has been helped in so many ways. She attended a special needs school for more than 3 years, and is now being taught to read and write through FTC staff.",
    link: "",
  },
  {
    image: "./img/minos-d.jpg",
    name: "Minos D",
    age: "11",
    birthday: "Oct 14, 2014",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/opt-angelica.jpg",
    name: "Angelita A",
    age: "33",
    birthday: "Jun 6, 1992",
    story: "My Story",
    desc: "She has been diagnosed with Cerebral palsy, and also being mentally slow. Angi is mostly crippled in both legs, and has limited use of her hands. For many years when she was just a small child, all she did was beg for alms in the city marketplace, along with her brothers and sisters. When Frontline missionaries noticed her, they began helping Angie by carrying her to the FTC Daycare Center where street kids were being fed and ministered to each day. At first Angie\\'s mother did not allow her to go back, and preferred she remain on the streets to collect money. Eventually Social Services escalated the case, and the FTC staff were allowed to rescue Angie from a dangerous and abusive situation, and Angie was brought to the FTC care center permanently. Though limited mentally due to her particular disease, Angie is happy because she has been helped in so many ways. She attended a special needs school for more than 3 years, and is now being taught to read and write through FTC staff.",
    link: "",
  },
  {
    image: "./img/opt-mary-joy.jpg",
    name: "Mary Joy C.",
    age: "14",
    birthday: "Nov 2, 2011",
    story: "My Story",
    desc: "Mary Joy is 12 years old. She, her sister and cousin came into our care when a pastora from a nearby community contacted the leadership of Frontline about a situation of abuse. After investigation by our social worker, we were able to bring them to the safety of our Face The Children program. After a two week orientation, Mary Joy has now joined our home with the other children of FTC. She is a cheerful person and is looking forward to enrolling in the new school year",
    link: "",
  },
  {
    image: "./img/opt-leam.jpg",
    name: "Carl Leam N.",
    age: "12",
    birthday: "Apr 25, 2013",
    story: "My Story",
    desc: "Leam came into our care in February 2024 after his father was detained in jail and his mother abandoned him. He was found roaming the streets of Sto. Tomas with his younger brother. He is currently being assessed for his educational level and will be enrolled at FCA (Frontline Christian Academy) this coming school year.",
    link: "",
  },
  {
    image: "./img/opt-charisse.jpg",
    name: "Charissa N.",
    age: "9",
    birthday: "Nov 6, 2016",
    story: "My Story",
    desc: "Charice and her siblings recently came into our care after their mother abandoned them. Their father is currently detained in jail. Charice was rescued from the streets of Calamba where she was roaming and begging for food. She is currently being assessed for her educational level and will be enrolled at FCA (Frontline Christian Academy) for the 2024/2025 school year.",
    link: "",
  },
  {
    image: "./img/chelsey-b.jpg",
    name: "Chelsey B",
    age: "9",
    birthday: "Jan 8, 2016",
    story: "My Story",
    desc: "Chelsey  was neglected and then abandoned by her parents.  When the mother and father separated Chelsey and her siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact. Her brother, JL, became the one who cared for his siblings.  Chelsey is enrolled in grade 2 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/opt-shiela.jpg",
    name: "Shiela Mariel S",
    age: "16",
    birthday: "Apr 9, 2009",
    story: "My Story",
    desc: "Shiela is third among five siblings. When she was found, she was malnourished and underweight. She used to roam around the streets with her brothers and sister, begging for food and other daily needs. Due to their povety situation, her mother was unable to earn a living for them. Her youngest sibling, who was then newly born, required most of her mother's attention. Shiela and her siblings were brought to Face the Children by the Social Services, and entered the FTC Interim Center along January 27, 2014. We have seen her grow and blossom into a happy girl, who enjoys playing with others and learning in the school.",
    link: "",
  },
  {
    image: "./img/opt-CIELITAHINE.jpg",
    name: "Cielitahine D",
    age: "15",
    birthday: "Feb 25, 2010",
    story: "My Story",
    desc: "Celine, along with her brother, were brought to Face the Children by the government Social Services (DSWD). Her story is one of malnourishment, abandonment by her father, and left only to the care of her mother. Her mother, however, is deaf and mute and had no job or any other source of income. Because of this, the children would go out and beg jeepney passengers for money, despite the many dangers they would encounter. The mother could not change this need for begging by the children, because the kids were literally starving. Now, in our care, Celine is healthy, safe, and doing very well in her studies at our school, Frontline Christian Academy.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
  {
    image: "./img/John-luke-b.jpg",
    name: "John Luke B",
    age: "12",
    birthday: "Jul 3, 2013",
    story: "My Story",
    desc: "John Luke, or JL, as he is called by his friends was neglected and then abandoned by his parents.  When the mother and father separated JL and his siblings were in the care of their mother.  The mother went to work overseas and left them in the care of another man who abandoned them.  The mother does not respond to contact.  JL is enrolled in grade 3 at Frontline Christian Academy and is interacting well within Face the Children.",
    link: "",
  },
];
